version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

  loki:
      image: grafana/loki:latest
      container_name: loki
      ports:
        - "3100:3100"
      volumes:
        - loki-data:/loki
      command: -config.file=/etc/loki/local-config.yaml

  python-log-monitor:
    build:
      context: ./python-log-monitor
    container_name: python-log-monitor
    volumes:
      - "/c/Program Files/PostgreSQL/17/data/log:/logs/postgresql_logs"
    depends_on:
      - loki

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
